import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import puppeteer from "puppeteer";
import { supabaseUserServer } from "@/lib/supabase";

/**
 * Export report as PDF using Puppeteer
 */
export async function POST(request) {
  let browser = null;
  
  try {
    console.log("[PDF Export] Starting export process");
    
    // Check authentication
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json(
        { error: "Unauthorized" },
        { status: 401 }
      );
    }

    const { ideaId, reportData, ideaData } = await request.json();
    
    if (!ideaId || !reportData || !ideaData) {
      return NextResponse.json(
        { error: "Missing required fields: ideaId, reportData, ideaData" },
        { status: 400 }
      );
    }

    console.log("[PDF Export] Launching browser");
    
    // Launch Puppeteer browser
    browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-accelerated-2d-canvas",
        "--no-first-run",
        "--no-zygote",
        "--single-process",
        "--disable-gpu"
      ]
    });

    const page = await browser.newPage();
    
    // Set viewport for consistent rendering
    await page.setViewport({ width: 1200, height: 800 });

    console.log("[PDF Export] Generating HTML content");
    
    // Generate HTML content for the report
    const htmlContent = generateReportHTML(ideaData, reportData);
    
    // Set content and wait for rendering
    await page.setContent(htmlContent, { 
      waitUntil: "networkidle0",
      timeout: 30000 
    });

    console.log("[PDF Export] Generating PDF");
    
    // Generate PDF
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: {
        top: "20mm",
        right: "15mm",
        bottom: "20mm",
        left: "15mm"
      },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 10px; width: 100%; text-align: center; color: #666;">
          <span>${ideaData.title} - Business Report</span>
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 10px; width: 100%; text-align: center; color: #666;">
          <span>Generated by IdeaVault - Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `
    });

    console.log("[PDF Export] PDF generated successfully");

    // Return PDF as response
    return new NextResponse(pdf, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${ideaData.title.replace(/[^a-zA-Z0-9]/g, "_")}_report.pdf"`,
        "Content-Length": pdf.length.toString()
      }
    });

  } catch (error) {
    console.error("[PDF Export] Error:", error);
    return NextResponse.json(
      { error: `Failed to export PDF: ${error.message}` },
      { status: 500 }
    );
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

/**
 * Generate HTML content for PDF export
 */
function generateReportHTML(ideaData, reportData) {
  const businessConcept = reportData.business_concept || {};
  const marketIntelligence = reportData.market_intelligence || {};
  const productStrategy = reportData.product_strategy || {};
  const goToMarket = reportData.go_to_market || {};
  const financialFoundation = reportData.financial_foundation || {};
  const evaluation = reportData.evaluation || {};

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${ideaData.title} - Business Report</title>
      <style>
        body {
          font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          text-align: center;
          border-bottom: 3px solid #3b82f6;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .title {
          font-size: 28px;
          font-weight: bold;
          color: #1e40af;
          margin-bottom: 10px;
        }
        .subtitle {
          font-size: 16px;
          color: #6b7280;
        }
        .section {
          margin-bottom: 30px;
          page-break-inside: avoid;
        }
        .section-title {
          font-size: 20px;
          font-weight: bold;
          color: #1e40af;
          border-bottom: 2px solid #e5e7eb;
          padding-bottom: 8px;
          margin-bottom: 15px;
        }
        .subsection {
          margin-bottom: 15px;
        }
        .subsection-title {
          font-size: 16px;
          font-weight: 600;
          color: #374151;
          margin-bottom: 8px;
        }
        .content {
          margin-bottom: 10px;
        }
        .list {
          margin-left: 20px;
        }
        .list li {
          margin-bottom: 5px;
        }
        .badge {
          display: inline-block;
          padding: 4px 8px;
          background-color: #dbeafe;
          color: #1e40af;
          border-radius: 4px;
          font-size: 12px;
          font-weight: 500;
          margin-right: 8px;
        }
        .metrics {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 15px;
          margin: 15px 0;
        }
        .metric {
          padding: 15px;
          background-color: #f9fafb;
          border-radius: 8px;
          border-left: 4px solid #3b82f6;
        }
        .metric-value {
          font-size: 18px;
          font-weight: bold;
          color: #1e40af;
        }
        .metric-label {
          font-size: 12px;
          color: #6b7280;
          text-transform: uppercase;
        }
        @media print {
          body { margin: 0; }
          .section { page-break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">${ideaData.title}</div>
        <div class="subtitle">
          <span class="badge">${ideaData.category || "Technology"}</span>
          <span class="badge">${ideaData.difficulty || "Medium"}</span>
          <span class="badge">${ideaData.target_audience || "General"}</span>
        </div>
        <div style="margin-top: 10px; color: #6b7280; font-size: 14px;">
          Generated on ${new Date().toLocaleDateString()}
        </div>
      </div>

      <div class="section">
        <div class="section-title">Business Concept</div>
        <div class="subsection">
          <div class="subsection-title">Elevator Pitch</div>
          <div class="content">${businessConcept.elevator_pitch || ideaData.description}</div>
        </div>
        <div class="subsection">
          <div class="subsection-title">Problem Statement</div>
          <div class="content">${businessConcept.problem_statement || "Addressing key market challenges"}</div>
        </div>
        <div class="subsection">
          <div class="subsection-title">Solution Overview</div>
          <div class="content">${businessConcept.solution_overview || "Innovative solution approach"}</div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">Market Intelligence</div>
        <div class="subsection">
          <div class="subsection-title">Market Size</div>
          <div class="content">${marketIntelligence.market_size || "Significant market opportunity"}</div>
        </div>
        ${marketIntelligence.market_trends ? `
        <div class="subsection">
          <div class="subsection-title">Market Trends</div>
          <ul class="list">
            ${marketIntelligence.market_trends.map(trend => `<li>${trend}</li>`).join("")}
          </ul>
        </div>
        ` : ""}
      </div>

      <div class="section">
        <div class="section-title">Product Strategy</div>
        ${productStrategy.core_features ? `
        <div class="subsection">
          <div class="subsection-title">Core Features</div>
          <ul class="list">
            ${productStrategy.core_features.map(feature => `<li><strong>${feature.name}:</strong> ${feature.description}</li>`).join("")}
          </ul>
        </div>
        ` : ""}
      </div>

      <div class="section">
        <div class="section-title">Financial Projections</div>
        ${financialFoundation.revenue_projections ? `
        <div class="metrics">
          ${financialFoundation.revenue_projections.map(proj => `
            <div class="metric">
              <div class="metric-value">${proj.amount}</div>
              <div class="metric-label">${proj.year}</div>
            </div>
          `).join("")}
        </div>
        ` : ""}
      </div>

      <div class="section">
        <div class="section-title">Evaluation & Recommendations</div>
        ${evaluation.strengths ? `
        <div class="subsection">
          <div class="subsection-title">Key Strengths</div>
          <ul class="list">
            ${evaluation.strengths.map(strength => `<li>${strength}</li>`).join("")}
          </ul>
        </div>
        ` : ""}
        ${evaluation.risks ? `
        <div class="subsection">
          <div class="subsection-title">Potential Risks</div>
          <ul class="list">
            ${evaluation.risks.map(risk => `<li>${risk}</li>`).join("")}
          </ul>
        </div>
        ` : ""}
      </div>
    </body>
    </html>
  `;
}
